### ISSUE TITLE
Error with installation 

### ISSUE THREAD

**Issue by jayantrawat** [bear-react-carousel/bear-react-carousel.github.io#1]
I'm creating a react js project using typescript and when I'm installing bear-react-carousel I'm getting following error

```
`./node_modules/bear-react-carousel/dist/bear-react-carousel.es.js 1106:33
Module parse failed: Unexpected token (1106:33)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const t = tr(window.innerWidth, Object.keys(e).map(Number));
|   let i = r;
>   t > 0 && (i = Object.assign(r ?? {}, e[t]));
|   const o = i.slidesPerView === "auto" ? 1 : Ge(i.slidesPerView, 1);
|   return { ...i,`
```

my tsconfig

````

{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ],
  "extends": "./tsconfig.paths.json",
  "paths": {
    "@mui/styled-engine": [
      "./node_modules/@mui/styled-engine-sc"
    ]
  },
  "rules": {
    "no-restricted-imports": [
      "error",
      {
        "patterns": [
          "@mui/*/*/*"
        ]
      }
    ]
  }
}
```

`

**Comment by imagine10255** [comment]
Hi,

I want to confirm your `node version`?
I tried to create a cra-ts version from scratch without any problems. Have you tried creating it from a clean version?

```bash
$ npx create-react-app my-app --template typescript
$ cd my-app
$ yarn add bear-react-carousel
$ yarn start
```


```json
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.52",
    "@types/react": "^18.2.21",
    "@types/react-dom": "^18.2.7",
    "bear-react-carousel": "^4.0.13",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
```

**Comment by jayantrawat** [comment]
My node version is `v18.17.1`. 


`"@types/jest": "^26.0.15",
    "@types/node": "^16.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",`

**Comment by jayantrawat** [comment]
> @jayantrawat Hi,
> 
> I want to confirm your `node version`? I tried to create a cra-ts version from scratch without any problems. Have you tried creating it from a clean version?
> 
> ```shell
> $ npx create-react-app my-app --template typescript
> $ cd my-app
> $ yarn add bear-react-carousel
> $ yarn start
> ```
> 
> ```json
>     "@types/jest": "^27.5.2",
>     "@types/node": "^16.18.52",
>     "@types/react": "^18.2.21",
>     "@types/react-dom": "^18.2.7",
>     "bear-react-carousel": "^4.0.13",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "react-scripts": "5.0.1",
>     "typescript": "^4.9.5",
> ```
> 
> Or, could you push it to GitHub so I can try it out?

My node version is v18.17.1.

`"@types/jest": "^26.0.15", "@types/node": "^16.0.0", "@types/react": "^17.0.0", "@types/react-dom": "^17.0.0",`

**Comment by imagine10255** [comment]
@jayantrawat 

I can confirm that my current new version only supports React 18 or above. Can you please upgrade the React version? Or create a new environment cra React 18 and migrate to it?

**Comment by jayantrawat** [comment]
Got it thanks, any version support for 17?

**Comment by imagine10255** [comment]
@jayantrawat 
your can use v1.2.17, but the doc provided now cannot be matched.
